### ISSUE TITLE
Please issue a release tag (e.g. 1.0.0)

### ISSUE THREAD

**Issue by fmunteanu** [lyft/flyte#114]
Is it possible to create a release? It will be a lot easier to track changes and make sure we avoid deployment issues.
https://github.com/lyft/flyte/releases

**Comment by EngHabu** [comment]
Hi Floren,
Thanks for you request. We are working on an overall release process. For the time being, the individual components, namely: https://github.com/lyft/flytepropeller/releases, https://github.com/lyft/flyteadmin/releases, https://github.com/lyft/flytekit/releases, https://github.com/lyft/flyteconsole/releases, https://github.com/lyft/datacatalog/releases, https://github.com/lyft/flyteplugins/releases, https://github.com/lyft/flytestdlib/releases, https://github.com/lyft/flyteidl/releases

master of Flyte repo will always have compatible versions of all the above components in: https://github.com/lyft/flyte/blob/master/deployment/sandbox/flyte_generated.yaml

**Comment by EngHabu** [comment]
If you do have opinions/suggestions @fmunteanu about how that should look like or good practices (from prior experience) that you would like to share, that's most welcome!

The current thinking is that these individual components will continue to cut rapid releases as they have been... with Flyte repo releases being a cumulation of a bunch of these when the delta is significant enough to cut a new release. Still working on quantifying what's significant though, a breaking change definitely is, perhaps time-based measure? complexity? "importance" of features... etc.

**Comment by kumare3** [comment]
We have for now decided to have a monthly release train for github/lyft/flyte releases. We will iterate individual components independently. We deploy Flyte continuously internally at Lyft, but we will cut lyft/flyte releases only when we believe it is absolutely stable. Thank you for reaching out, keep a look out for seeing the release process that will be posted soon.
