### ISSUE TITLE
Define 3rd party plugins structure and integration

### ISSUE THREAD

**Issue by EngHabu** [lyft/flyte#117]
A few 3rd party plugins are underway, we need to define:

1) Where should they be written? mono-repo? individual repos?
2) Directory structure for different integration points (SDK Task Extensions, Backend Plugins... etc.)
3) How should they be built and released
4) How do core components discover and load these plugins
5) How can Flyte administrators control which plugins can/can't be loaded

**Comment by kumare3** [comment]
Closing this out, as this is a big project
