### ISSUE TITLE
Cloudwatch logs plugin does not work for default AWS Log configuration

### ISSUE THREAD

**Issue by kumare3** [lyft/flyte#133]
EKS recommends using fluentD -> cloudwatch for monitoring container logs, as described here
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs.html

Flyte has a logs plugin for fluentD, that create log links to cloudwatch. But, these log links do not work with EKS out ouf the box. 
following the EKS recommended fluentD setup has logs in the format
<podname>_<namespace>_<container_name>.

Thus the format should be configurable in the log plugin

**Comment by kumare3** [comment]
We will work on this in 0.5.0

**Comment by EngHabu** [comment]
Done
