### ISSUE TITLE
Use a consistent Execution id format between CLI and UI

### ISSUE THREAD

**Issue by schottra** [lyft/flyte#142]
It's helpful to be able to copy/paste execution ids between the CLI and UI. For example, a user can launch an execution via the CLI and then want to open the UI to monitor its progress.

At the moment, the CLI uses URN formats (`project:domain:name`) and the UI is using a URL/path (`project/domain/name`). It's a minor difference, but enough that users have to manually edit the values when pasting.

**Comment by EngHabu** [comment]
Bug bankruptcy
