### ISSUE TITLE
Filter executions by user/principal

### ISSUE THREAD

**Issue by schottra** [lyft/flyte#143]
When AuthZ is enabled, we will be automatically attaching `principal` values to executions when launched via the CLI.
A useful data point to filter on is the principal which launched the execution. This would involve:
* Potentially adding another (optional?) column to the WorkflowExecutions table
* Adding support in Admin for filtering on the `principal` value
* Adding a filter button above the executions table. Initial thoughts are that it will work similar to the `version` filter (a simple search box), but that it would also include a "me"-type button that sets the value to the logged-in user

**Comment by EngHabu** [comment]
Bug bankruptcy
