### ISSUE TITLE
Add most recent versions to the Version filter above the Workflow Executions table

### ISSUE THREAD

**Issue by schottra** [lyft/flyte#144]
The Version filter is currently a simple search box. This is because generating a list of available version strings isn't currently possible via Admin and the overhead of adding that feature seemed greater than the value. (We *could* just request all Workflow objects and grab the version from each. But the resulting objects are rather large, so it's really inefficient)

However, what we *can* do is pull in the workflow version search combobox used in the Launch form. That component compromises between the two by listing the last 10 version strings and then allowing for an autocomplete functionality when the user types.

**Comment by EngHabu** [comment]
Bug bankruptcy
