### ISSUE TITLE
Propeller unable to initialize Redis client

### ISSUE THREAD

**Issue by adriangay** [lyft/flyte#153]
I have deployed Flyte in Kubernetes v1.14.8 in Docker Desktop v2.1.0.5. The Ui starts up but laucnhing the demo EdgeDetector workflow return status unknown. looking at the deployment, ```flytepropeller``` is ```crashloopbackoff```. The logs show the reason is connection refused to the Redis pod... help! Thanks :)

```
{"json":{"src":"resourcemanager_util.go:23"},"level":"info","msg":"Using Redis based resource manager","ts":"2020-01-08T15:38:34Z"}
{"json":{"src":"redis_client.go:22"},"level":"error","msg":"Error creating Redis client at [redis-resource-manager.flyte:6379]. Error: dial tcp 10.100.0.82:6379: connect: connection refused","ts":"2020-01-08T15:38:35Z"}
{"json":{"src":"resourcemanager_util.go:27"},"level":"error","msg":"Unable to initialize a redis client for the resource manager: [dial tcp 10.100.0.82:6379: connect: connection refused]","ts":"2020-01-08T15:38:35Z"}
{"json":{"src":"controller.go:96"},"level":"panic","msg":"dial tcp 10.100.0.82:6379: connect: connection refused","ts":"2020-01-08T15:38:35Z"}
panic: (*logrus.Entry) (0x1d81ea0,0xc0002c89a0)
```

**Comment by adriangay** [comment]
my apologies... it seems that an existing istio service mesh based deployment in the same K8s interferes with the 'NodePort' Flyte deployment. ```flytepropeller``` is now starting up ok :)

**Comment by kumare3** [comment]
Thank you for closing the issue @adriangay
