### ISSUE TITLE
docker run - sandbox is failing

### ISSUE THREAD

**Issue by sankarvishnu** [lyft/flyte#156]
Getting the follow running the example from the docs. Anyone have ideas why?

docker run --network host -e FLYTE_PLATFORM_URL='127.0.0.1:30081' lyft/flytesnacks:v0.1.0 pyflyte -p flytesnacks -d development -c sandbox.config register workflows
Using configuration file at /app/sandbox.config
Flyte Admin URL 127.0.0.1:30081
Running task, workflow, and launch plan registration for flytesnacks, development, ['workflows'] with version 46045e6383611da1cb763d64d846508806fce1a4
Registering Task:                workflows.edges.edge_detection_canny
Traceback (most recent call last):

Refer the issue here -

[https://stackoverflow.com/questions/59644701/lyft-flyte-errors-on-startup-following-docs](url)

**Comment by yu-iskw** [comment]
I have the same issue on my machine.
I just tried to run the command in [Quick Start Examples — Flyte 0\.0\.1 documentation](https://lyft.github.io/flyte/user/getting_started/examples.html#registration).

## Environment
```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.13
 Git commit:        6a30dfc
 Built:             Thu Sep 12 02:54:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:55:51 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Error Message
```
$ docker run --network host -e FLYTE_PLATFORM_URL="127.0.0.1:30081" lyft/flytesnacks:v0.1.0 pyflyte -p flytesnacks -d development -c sandbox.config register workflows

Using configuration file at /app/sandbox.config
Flyte Admin URL 192.168.99.104:30081
Running task, workflow, and launch plan registration for flytesnacks, development, ['workflows'] with version 46045e6383611da1cb763d64d846508806fce1a4
Registering Task:                workflows.edges.edge_detection_canny
Traceback (most recent call last):
  File "/app/venv/bin/pyflyte", line 11, in <module>
    sys.exit(main())
  File "/app/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/app/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/app/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/app/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/venv/lib/python3.6/site-packages/flytekit/clis/sdk_in_container/register.py", line 86, in workflows
    register_all(project, domain, pkgs, test, version)
  File "/app/venv/lib/python3.6/site-packages/flytekit/clis/sdk_in_container/register.py", line 24, in register_all
    o.register(project, domain, name, version)
  File "/app/venv/lib/python3.6/site-packages/flytekit/common/exceptions/scopes.py", line 158, in system_entry_point
    return wrapped(*args, **kwargs)
  File "/app/venv/lib/python3.6/site-packages/flytekit/common/tasks/task.py", line 141, in register
    _engine_loader.get_engine().get_task(self).register(id_to_register)
  File "/app/venv/lib/python3.6/site-packages/flytekit/engines/flyte/engine.py", line 234, in register
    self.sdk_task
  File "/app/venv/lib/python3.6/site-packages/flytekit/clients/friendly.py", line 50, in create_task
    spec=task_spec.to_flyte_idl()
  File "/app/venv/lib/python3.6/site-packages/flytekit/clients/raw.py", line 12, in handler
    return fn(*args, **kwargs)
  File "/app/venv/lib/python3.6/site-packages/flytekit/clients/raw.py", line 77, in create_task
    return self._stub.CreateTask(task_create_request)
  File "/app/venv/lib/python3.6/site-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/app/venv/lib/python3.6/site-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1579659110.981399324","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3876,"referenced_errors":[{"created":"@1579659110.981389699","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":395,"grpc_status":14}]}"
```

**Comment by andrisole92** [comment]
@yu-iskw I have the same issue.

**Comment by adinin** [comment]
same.

ran
```bash
minikube start
kubectl create -f https://raw.githubusercontent.com/lyft/flyte/master/deployment/sandbox/flyte_generated.yaml
minikube tunnel
docker run --network host -e FLYTE_PLATFORM_URL='192.168.99.125:30081' lyft/flytesnacks:v0.1.0 pyflyte -p flytesnacks -d development -c sandbox.config register workflows 
#FLYTE_PLATFORM_URL ip is from the output of minikube tunnel
```

**Comment by apryiomka** [comment]
Getting the same error in both docker run and k8s on mac:
`flyte-cli -h localhost:30081 register-project --identifier myuniqueworkflow --name FriendlyWorkflowName -d "This is awesome workflow"`

> E0205 10:57:44.523901000 140735709533056 ssl_transport_security.cc:1246] Handshake failed 
> with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
> E0205 10:57:44.528898000 140735709533056 ssl_transport_security.cc:1246] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
> Traceback (most recent call last):
>   File "/usr/local/bin/flyte-cli", line 10, in <module>
>     sys.exit(_flyte_cli())
>   File "/Users/aliaksandrp/Library/Python/3.7/lib/python/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/aliaksandrp/Library/Python/3.7/lib/python/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/Users/aliaksandrp/Library/Python/3.7/lib/python/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Users/aliaksandrp/Library/Python/3.7/lib/python/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/aliaksandrp/Library/Python/3.7/lib/python/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/flytekit/clis/flyte_cli/main.py", line 1502, in register_project
>     client.register_project(_Project(identifier, name, description))
>   File "/usr/local/lib/python3.7/site-packages/flytekit/clients/friendly.py", line 858, in register_project
>     project=project.to_flyte_idl(),
>   File "/usr/local/lib/python3.7/site-packages/flytekit/clients/raw.py", line 78, in handler
>     return fn(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/flytekit/clients/raw.py", line 558, in register_project
>     return self._stub.RegisterProject(project_register_request, metadata=self._metadata)
>   File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 824, in __call__
>     return _end_unary_response_blocking(state, call, False, None)
>   File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 726, in _end_unary_response_blocking
>     raise _InactiveRpcError(state)
> grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
> 	status = StatusCode.UNAVAILABLE
> 	details = "failed to connect to all addresses"
> 	debug_error_string = "{"created":"@1580929064.529186000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1580929064.529162000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_status":14}]}"

**Comment by kumare3** [comment]
We have discussed this in the channel, let me try and distill the information here,

**Comment by sankarvishnu** [comment]
Do we have any solution to this?

**Comment by jonathanburns** [comment]
Hello all,

Apologies for the trouble and for the delay.

During registration, the SDK makes a call to the Flyte API to register the workflow.

It looks like in all cases above, the SDK is unable to access the API endpoint.

Some of you have specified the API endpoint as `127.0.0.1:30081` (localhost), others have specified `192.168.99.125:30081` (I assume this is your minikube IP address).

Let's make sure that the machine which is running your docker container can access this endpoint.

`curl {flyteIP:30081}/api/v1/projects}`

If you cannot access this endpoint, let's figure out why that is not working. Also, feel free to "@" me in the Flyte slack channel if you'd like.

PS, I don't think you'll need any `minikube tunnel` in order to make this work @adinin (I've gotten it to work in minikube without that)

**Comment by kumare3** [comment]
I think the problem is in FLYTE_PLATFORM_URL='127.0.0.1:30081'.Minikube runs in VM on OSX. When you run docker run --network host, the docker daemon shares the networking namespace with this host - https://docs.docker.com/network/host/ Thus if you have the docker daemon and Kubernetes running on the same host (not a VM), you should be able to refer to services (nodeport) or ingress on Kubernetes using 127.0.0.1. But, since minikube runs in a VM on osx, you will need to use minikube ip to find the ip address of the minikube machine and then set

FLYTE_PLATFORM_URL=':30081'

**Comment by kumare3** [comment]
We will add this to the documentation in the next milestone

**Comment by kumare3** [comment]
This is in the documentation now https://lyft.github.io/flyte/administrator/install/getting_started.html
