### ISSUE TITLE
Graph view in flyteconsole not working

### ISSUE THREAD

**Issue by giordyb** [lyft/flyte#179]
Hi, 
I just updated to the lastest release and flyteconsole 0.3.1 stopped showing the graph view, the error that I am getting is 

`TypeError: a.dratify is not a function`

**Comment by schottra** [comment]
Thanks for logging this. I updated dependencies recently, and it looks like a few of the libraries had some backwards-incompatible changes in minor version updates. I'm going to revert those libraries back to known working versions for now.

**Comment by schottra** [comment]
Fixed in v0.3.2
