### ISSUE TITLE
abort on spark plugin didn't delete k8s crd when workflow is failed.

### ISSUE THREAD

**Issue by chengxuanw** [lyft/flyte#188]

**Comment by kumare3** [comment]
@chengxuanw can you add more details here please? I cannot reproduce this

**Comment by chengxuanw** [comment]
@kumare3 Yeah. it is gone now. but I did see one time, after the spark task is failed, the spark driver ui is still accessible. since we also have GC behind it, should be fine. 

Feel free to resolve it.
