### ISSUE TITLE
Support run-to-completion flag

### ISSUE THREAD

**Issue by datability-io** [lyft/flyte#191]
Right now, if any of the tasks in a workflow fails, Flyte will fail the entire workflow.  We would like to have a flag to let the Flyte continue to run whatever tasks that are not affected by the failed tasks.

In the following example, if task 3 fails, task 5 will be marked `won't run`.  While task 1, 2, 4 should continue to run.

![image](https://user-images.githubusercontent.com/17309187/75929984-8583d880-5e26-11ea-8250-b5bf98dd5bbb.png)

**Comment by kumare3** [comment]
This is actually available in a different way. This is not available in flytekit.

Lets take your example, @datability-io,
if task-3 fails, the output it generates is fed into task-5. So it is theoretically not possible to run task-5, as by definition no data was generated by task-3 to pass on to 5.

But, there are situations when you may want to run task-5 as a cleanup or as a finalizer, even if task-3 fails. In this scenario, there is not real dependency between the tasks in terms of data producer and consumer. This is actually a supported use case in the Flyte engine. the semantics are like try/catch in programming languages.

So the code will be changed so
```
try:
  task-1 = 
  task-2 =
  task-4(task-1, task-2)
  task-3 = 
catch: 
   task-5 =
```

In your example do you think this way of constructing the workflow would love your problem?

**Comment by wild-endeavor** [comment]
i don't think there's anything special about task-5 though.  the author shouldn't have to know a priori which one might fail.  it's just how propeller progresses through the nodes.  instead of failing the workflow when a single node fails, fail the workflow after as much progress as possible has been made.  I don't see how this changes the fundamental compute constructs that Flyte offers so I'm okay with this feature in theory.

**Comment by datability-io** [comment]
@kumare3, for task 5, I was not expecting it to run and I don't need it to run in my use case.  In my example, I was intended to say in that case, we could just mark task 5 as `won't run`.  However, for task 1, 2 and 4, they should continue to run as they don't depend on task 3.

**Comment by EngHabu** [comment]
In this example, what I'm hearing is, you want to guarantee that tasks 1, 2, 3 and 4 run and are allowed to finish, even if task 3 failed before anything else... right?

I agree with Yee that, in theory, there is no reason this won't be an option... specially given that caching is a supported first-level construct, so after the user fixes task 3 and rerun the entire workflow, tasks 1, 2 and 4 will be cached and skipped.

**Comment by datability-io** [comment]
> In this example, what I'm hearing is, you want to guarantee that tasks 1, 2, 3 and 4 run and are allowed to finish, even if task 3 failed before anything else... right?

Yes

**Comment by EngHabu** [comment]
For context, we have discussed this early on when we were deciding the failure behavior (and adding the failure node) and opt'd for the simpler behavior until a real use-case arises for a more customizable strategy.

There is something to be said about whether to allow this behavior only for tasks marked as cacheable vs any. **Any preferences on this, @wild-endeavor, @kumare3, @datability-io?** The only scenario I can think of where you will want to continue even if task1, 2 and 4 are not cacheable is if they have side-effects. Which is a pattern we would like to discourage....

In terms of how:
1. Maybe adding FailureHandlingStrategy field on the WorkflowTemplate with [Unknown, Fail, Continue, ContinueIfCacheable] with Unknown and Fail behave like they do today.

* Even with this flag, the overall phase of the workflow will eventually be `Failed`.

2. Or borrowing from [ArrayTasks's min_successes](https://github.com/lyft/flyteidl/blob/master/protos/flyteidl/plugins/array_job.proto#L23) maybe allow that at Workflow and/or Node levels?

* The behavior with Array Tasks is if min_successes is met, the overall phase becomes `Success`.

**Comment by datability-io** [comment]
> Even with this flag, the overall phase of the workflow will eventually be Failed

Maybe `Some Failed`?

**Comment by datability-io** [comment]
In our use case, we cannot really tell something like `min_successes`.  Also in our case, the output for task 1, 2 and 3 are more like side-effects.  Those tasks write data to Hive tables and task 4 and 5 use the data from the corresponding Hive tables.

**Comment by deektionary** [comment]
+1 to creating this flag. It would be very useful for mapworkflows to switch to flytekit

**Comment by feiyu-meng** [comment]
+1 to this feature. It is crucial for my use case. We could like to have one master workflow for all our production cases which shared common components. Ideally, a task failure should only impact its downstream. other tasks should run to completion.

**Comment by wild-endeavor** [comment]
With respect to the comment @EngHabu - my preference is any node.  The reason is that there is one side effect that is perfectly acceptable in Flyte, the output of a task.  The user might not care to cache the output, but does care to see what that output is.  Since I don't think we want to discourage this, my vote is with any.

**Comment by feiyu-meng** [comment]
Hey @EngHabu , do you have an estimation on this feature?

**Comment by EngHabu** [comment]
Hi @feiyu-meng, I've merged all required changed and deployed this change to our production clusters. I'm in the process of adding it to our docs before closing this issue.

**Comment by feiyu-meng** [comment]
@EngHabu thanks! will try it out this week!

**Comment by deektionary** [comment]
thank you @EngHabu!!

**Comment by EngHabu** [comment]
Done. Please let me know when you give it a shot if you have any trouble...
