### ISSUE TITLE
Add support for querying Presto

### ISSUE THREAD

**Issue by lu4nm3** [lyft/flyte#203]
**Why would this plugin be helpful to the Flyte community**
Presto is a query engine, similar to Hive, that is compatible with a lot of different data stores using a pluggable connector model. At a high level, Presto tends to run a lot faster and more efficiently than Hive. Due to its up and coming popularity, especially within Lyft, it would be beneficial if Flyte had native support for querying it.

**Type of Plugin**
- [X] Web Service (e.g. AWS Sagemaker, GCP DataFlow, Qubole etc...)
- [ ] Kubernetes Operator (e.g. TfOperator, SparkOperator, FlinkK8sOperator, etc...)
- [ ] Customized Plugin using native kubernetes constructs
- [ ] Other

**Can you help us with the implementation?**
- [X] Yes
- [ ] No

**Additional context**

**Comment by wild-endeavor** [comment]
All of Luis's (public) PRs:

flyteidl - https://github.com/lyft/flyteidl/pull/45
flytekit - https://github.com/lyft/flytekit/pull/89
flytetools - https://github.com/lyft/flytetools/pull/9
flyteplugins - https://github.com/lyft/flyteplugins/pull/69
flytepropeller - https://github.com/lyft/flytepropeller/pull/96
flyte (configs)  - https://github.com/lyft/flyte/pull/204
