### ISSUE TITLE
[Feature] Store and retrieve system information associated with the execution

### ISSUE THREAD

**Issue by kumare3** [lyft/flyte#206]
**Motivation: Why do you think this is important?**
For an execution it is important for the administrator to know how the execution was executed, what placement decisions were taken etc. Sometimes this is useful for the user to and to help the user track down potential infrastructure issues

**Goal: What should the final outcome look like, ideally?**
There would be a UI/CLI/API to access placement information like the cluster used and any other system parameters.

**Describe alternatives you've considered**
access the databsase

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [x] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [x] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
NA

**Additional context**
NA

**Is this a blocker for you to adopt Flyte**
NA

**Comment by katrogan** [comment]
this is now done
