### ISSUE TITLE
[BUG] Finalize() for parent tasks in dynamic nodes gets called after the dynamic WF is done

### ISSUE THREAD

**Issue by EngHabu** [lyft/flyte#209]
**Describe the bug**
We have noticed that, at least sometimes, a plugin's `Finalize()` is not always getting called. This leads to resources held (e.g. Resource Manager tokens, pods) not being released.

**Expected behavior**
`Finalize()` should be a guaranteed step to be called.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [X] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
1. ...
2. ...

**Screenshots**

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [X] Cloud hosted
     * [X] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**
Similar to #202 but even with the fix, this continues to happen for some tasks.

**Comment by kumare3** [comment]
This is because for Dynamic nodes we do not call finalize for the parent node immediately after it is complete.

**Comment by kumare3** [comment]
This is available from v0.2.18 onwards
