### ISSUE TITLE
Tasks should be filterable by type in admin

### ISSUE THREAD

**Issue by katrogan** [lyft/flyte#215]
**Motivation: Why do you think this is important?**
This is helpful for analysis of tasks by type. Currently we store the type in the task closure but this is unavailable for filtering.

**Goal: What should the final outcome look like, ideally?**
Queries to admin filtering by task type should be supported.

**Describe alternatives you've considered**
Querying without filters and having clients unpack the closure proto and perform client-side filtering by type.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [x] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
Promote 'type' as a task model field in the admin db.

**Additional context**
N/A

**Is this a blocker for you to adopt Flyte**
N/A

**Comment by kumare3** [comment]
@katrogan is this implemented?

**Comment by katrogan** [comment]
Yes, closing
