### ISSUE TITLE
Support additional input types in the Launch UI

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#22]
We don't currently support list/map or some of the less common types. This task is to at least implement list/map and explore if there is anything we can do about supporting the other types.

**Comment by schottra** [comment]
This issue originally included implementation of collections. Since collections are more commonly used, they were implemented first. The remaining types are a lower priority, so I've updated the description and labels to reflect that.

**Comment by kumare3** [comment]
@schottra I think Launch is very highly used and hence having the breadth covered is probably very important.

**Comment by kumare3** [comment]
@schottra do we know which input types are remaining?

**Comment by schottra** [comment]
@kumare3 Currently, we have no support for:
* `Map`
* `Schema`
* `Struct`
* `Binary` (not sure we really plan to support this in any useful way)

We also do not support `Error`, but I don't expect that to be a type that you can actually accept as an input.

**Comment by schottra** [comment]
As of flyteconsole v0.17.0, Schema and Struct are now supported. I'm going to create a separate issue for Map and close this one out.
If we want to handle providing Binary values via the console, that should have its own issue as well.
