### ISSUE TITLE
Add support to specify NodeSelector value as part of k8s-array config

### ISSUE THREAD

**Issue by migueltol22** [lyft/flyte#220]
**Motivation: Why do you think this is important?**
It would be useful to ensure a plugin lands on a specific set of nodes using NodeSelector.

**Goal: What should the final outcome look like, ideally?**
As part of the config for k8s array we can set a key value pair for node selector.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [x] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
If you have ideas about the implementation please propose the change. If inline keep it short, if larger then you link to an external document.

**Additional context**

**Is this a blocker for you to adopt Flyte**
Please let us know if this makes it impossible to adopt Flyte

**Comment by EngHabu** [comment]
Can you elaborate as of why this can be useful? why only array tasks?

**Comment by migueltol22** [comment]
For our specific use case we have a set of nodes that are reserved instances and others that are spot and have labeled them appropriately. Because k8's array tasks behavior with spot instances is currently not handled correctly due to https://github.com/lyft/flyte/issues/190. We'd like to run these on nodes with reserved instances by using NodeSelector. 

In general this may be useful for all plugins  but this is the usecase we ran into.
