### ISSUE TITLE
Implement Branch Nodes in FlyteKit

### ISSUE THREAD

**Issue by EngHabu** [lyft/flyte#231]
**Motivation: Why do you think this is important?**
Statically declared WF branching allows users to write more concise flow control logic that can be visualized/debugged/analyzed statically.

**Goal: What should the final outcome look like, ideally?**
A pythonic-way of defining branches within a workflow that implements the [full flyte IDL spec](https://github.com/lyft/flyteidl/blob/master/protos/flyteidl/core/condition.proto). 

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [X] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
```
n1 = get_int(...)
node = flyte_if(n1).EqualsTo(5).then(task_1(...))
             .else_if().GreaterThan(10).then(lp_2(...))
             .else(default_case(...))
```

**Comment by kumare3** [comment]
This is now part of `v0.16.0b1`
