### ISSUE TITLE
[Feature] Add ability to hide deprecated workflows 

### ISSUE THREAD

**Issue by katrogan** [lyft/flyte#235]
**Motivation: Why do you think this is important?**
A frequent request from users arise when they stop developing a workflow, but it perpetually remains on the workflows list page e.g. https://example.com/console/projects/flytesnacks/workflows?domain=production
Unused workflows clutter the overview page as more workflows get added over time.

**Goal: What should the final outcome look like, ideally?**
It should be possible to tombstone (soft-delete) a workflow so that historical data can still be accessed but the workflow isn't necessarily shown in the workflow overviews page.

**Describe alternatives you've considered**
Hard-delete: not great because we lose historical data. Related artifacts will still reference the non-existent workflow, which could get confusing

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [x] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [x] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
Add an update call to set a workflow active or archived (default is active) much like what exists for updating launch plan statuses today. In FlyteAdmin store the active bit so that's filterable. In the UI call to list workflows add the `active` filter. Additionally, use auth to record who last updated a workflow since workflows are otherwise immutable and only the visibility can change

**Additional context**
_NA_

**Is this a blocker for you to adopt Flyte**
Please let us know if this makes it impossible to adopt Flyte

**Comment by katrogan** [comment]
cc @schottra does this sound reasonable to you?

**Comment by schottra** [comment]
@katrogan Yep, seems like a good approach. I have a few questions:
* Are we concerned that a single user can hide the workflows for all other users?
* Using `active`/`inactive` might imply that it's the same behavior as LaunchPlans, when really this is more of a "visible" / "not visible", or "in use" / "deprecated". Thoughts on using a different name for the property/column?

**Comment by katrogan** [comment]
thanks @schottra the whole point of this was that it's feasible now that we have auth and i forgot to add the audit mechanisms to the outline. mind taking another look? also updated to use "active" vs "archived"

**Comment by schottra** [comment]
Ah, so we would filter on `ne(archived, 1)`?

**Comment by katrogan** [comment]
perhaps something like `eq(state, active)` not sure if there's a better suggestion for calling the attribute `state`, however

**Comment by schottra** [comment]
Oh I see, it's not a flag, it's a string value? Got it, so yes we would filter on `eq(state, active)`. No idea on a better name for that. I think state is probably okay, just a little generic.
