### ISSUE TITLE
Allow users to exclude archived workflows in Flyte Console

### ISSUE THREAD

**Issue by schottra** [lyft/flyte#248]
Workflows can now be marked as "archived" in Admin. This allows users to clean up any deprecated workflows that they no longer wish to see in the UI. The UI needs to add support for only listing active workflows.

**Comment by EngHabu** [comment]
Is this something you are working on @schottra?

**Comment by schottra** [comment]
@EngHabu I'm not currently working on it. It's on the backlog, but there are a few larger things in front of it.

**Comment by schottra** [comment]
This was implemented by lyft/flyteconsole#71. Archived workflows no longer show in the list view.
