### ISSUE TITLE
[Feature] Implement run a single task in admin

### ISSUE THREAD

**Issue by katrogan** [lyft/flyte#256]
**Motivation: Why do you think this is important?**
A full-fledged description of the motivation for single task is described in https://github.com/lyft/flyte/issues/221. This specific feature proposal is unblock a v1 of the single task functionality by:

**Goal: What should the final outcome look like, ideally?**
1. Creating an endpoint in the admin service to run a single task described in PART 4 of the linked issue (https://github.com/lyft/flyte/issues/221)
2. Implementing the endpoint to assemble a [non-active workflow](https://github.com/lyft/flyte/issues/235) definition that includes start node -> single task -> end node as its structure
3. Admin then creates a new workflow CRD for this 'phantom' workflow definition and its execution proceeds as normal.

**Describe alternatives you've considered**
Again https://github.com/lyft/flyte/issues/221 comprehensively documents the full sequence of steps to implement the alternative. This proposal is meant to unblock work for (sagemaker) notebook tasks and others.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [x] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
N/A

**Additional context**
N/A

**Is this a blocker for you to adopt Flyte**
N/A

**Comment by katrogan** [comment]
@kumare3 what do you think?

**Comment by katrogan** [comment]
cc @EngHabu

**Comment by kumare3** [comment]
So if you assemble a workflow without a WorkflowID, will the events work? I thought the events have a dependency on the workflow ID

**Comment by EngHabu** [comment]
What do you mean without a WorkflowID? it'll have a randomly generated WorkflowID it'll just persist in the DB as inactive Workflow. So you won't see it in the UI... but for all intents and purposes, it'll be usable by all components in the system.

**Comment by katrogan** [comment]
I think in the long-term @kumare3 your strategy as a reference entity for an execution not necessarily being a workflow might cause us to re-evaluate eventing validation. however this proposal would create a system-generated workflow skeleton so eventing and execution would proceed as normal

**Comment by katrogan** [comment]
To summarize what we discussed today, the proposed changes to admin in order to more easily migrate to the full implementation of single task execution will be:

- The [reference entity](https://github.com/lyft/flyteidl/blob/master/protos/flyteidl/admin/execution.proto#L210) in the CreateExecutionRequest will change to be of any resource type, rather than only a launch plan. Admin will validate that a reference launch plan or task exists based on the identifier [resource type](https://github.com/lyft/flyteidl/blob/master/protos/flyteidl/core/identifier.proto#L8)
- The executions table will now [optionally store a link](https://github.com/lyft/flyteadmin/blob/master/pkg/repositories/models/execution.go#L23) to the reference task id row. This will be a logical one-of, either an execution is tied to a launch plan or task identifier

Next steps:
- Clean up idl (https://github.com/lyft/flyte/issues/262) to make it less confusing given the redesigned flow

**Comment by katrogan** [comment]
@schottra this change may eventually affect the UI. Specifically https://github.com/lyft/flyteidl/blob/master/protos/flyteidl/admin/execution.proto#L210 may change so that is no longer necessarily a launch plan, but potentially a task.

Step 1 of this change will create a skeleton workflow for single task executions, so there will still be a reference workflow and no observable change from the console's perspective. But in the future, when https://github.com/lyft/flyte/issues/221 is checked in, will the UI be able to handle a single node, single task execution?

**Comment by schottra** [comment]
@katrogan My initial thoughts are that the following might be issues:
* I'm hoping we won't rename that proto property? That would probably break things. :grin: But also, introducing a new property and switching to a oneOf type behavior will also break things. We currently assume in a few places that an execution has a `launch_plan`, and that the launch plan has `expected_inputs` etc.
* The execution details page expects an execution to have a workflow and will probably fail to load both the NodeExecution list and the graph view, as they assume that all of the node information is stored in a workflow spec.
* If we are generating skeleton workflows, they will clutter the workflow names list. I know we have plans to hide non-'active' workflows, but that's not high priority at the moment. Even when that _is_ implemented, the plan was to allow users to toggle viewing all workflows, which would also be cluttered by the system-generated entries. Maybe we can add another state entry to indicate that a workflow was not created by a user?

**Comment by katrogan** [comment]
hey @schottra thanks for bringing these up

1. we're holding off on renaming the field. it won't necessarily break things, but will require code changes to update referencing the field on an idl upgrade
2. this proposal will still generate one workflow per execution. i think your overall concern will need to be addressed when we move to actually supporting referenced, launch tasks
3. good point! adding a system generated state sounds reasonable!
