### ISSUE TITLE
[BUG] If a task only specifies resource limit, admin sets the request to a value potentially lower than the limit

### ISSUE THREAD

**Issue by EngHabu** [lyft/flyte#264]
**Describe the bug**
If a task sets `memory_limit=200Mi`, admin will set the `memory_request=500Mi` since that's the default it's configured with. This creates an invalid spec. Limit has to be >= request.

**Expected behavior**
Admin should set request == limit if limit is set, or to the default if not... and should do the same for the limit (set it == request if not set or to the default limit if not set)

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [X] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [X] Cloud hosted
     * [X] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**
https://github.com/lyft/flyteadmin/blob/2a065109c8b14f560ef27aa74df67b157c52d9d1/pkg/manager/impl/execution_manager.go#L301-L303

**Comment by bnsblue** [comment]
@EngHabu Thank you for filing this bug
