### ISSUE TITLE
[BUG] Node timeout error should be tagged as an user error

### ISSUE THREAD

**Issue by surindersinghp** [lyft/flyte#277]
**Describe the bug**
Now we have "kind" field in the execution error, we should tag that as user error.

**Expected behavior**
correctly tagged as user.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [x] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Screenshots**

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [ ] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**

**Comment by kumare3** [comment]
this has been merged
