### ISSUE TITLE
[Feature] Ability to specify the description in workflow_class annotation

### ISSUE THREAD

**Issue by joannepolsky** [lyft/flyte#278]
**Motivation: Why do you think this is important?**
Flyte UI currently has the ability to show the description of a launch plan. However, updating the description is not completely straight forward. If we could define the metadata at the same point where we define the schema, it would simplify things greatly. The ask here would be to include a description as part of the `@workflow_class` annotation.

**Goal: What should the final outcome look like, ideally?**
Provide a fast and simple way for launch plan descriptions to be updated via the same/preferred mechanism used to define the schema, which is in code.

**Describe alternatives you've considered**
Calling the API directly is an alternative. However, additional scripts would be required, and significant code would need to be written to couple those descriptions with launch plans.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [X] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
Not at this time, but I can look into it.

**Additional context**
None.

**Is this a blocker for you to adopt Flyte**
Not a blocker, just a really really nice to have. Especially since the capability already exists, folks can take full advantage of the features if they are simplified.

**Comment by katrogan** [comment]
cc @wild-endeavor @matthewphsmith

**Comment by wild-endeavor** [comment]
@joannepolsky - is your interest in having a description be available on the launch plan?  on the workflow?  or both?  They are different entities.  Is the description for workflow ever displayed anywhere?

@katrogan could use your input here.  Currently the named `UpdateNamedEntity` endpoint takes any named entity.  This means tasks/workflows/launch plans can all have descriptions right?  Does Admin handle all of them correctly today?

**Comment by katrogan** [comment]
@wild-endeavor yes, admin handles description updates for all named entities (the cli can handle updating them all as well)

**Comment by wild-endeavor** [comment]
I would not be opposed to having the workflow_class decorator take a description field, but it should only be used for the workflow, not launch plans derived from the workflow.  For those, it should be part of the launch plan constructor.

What's unclear however is how this would be implemented.  The best way would probably involve a change on the Admin side - currently the registration endpoint does not allow specifying a description I don't think.

We'd have to either change the admin registration endpoints to allow specifying the `NamedEntityMetadata` field, or we'd have to make this two separate calls to admin in the registration process.  Not sure which one I'd prefer.

I don't think this is super high priority for us though, as the functionality to assign the description already exists, if manual.  Unless you want to work on it @joannepolsky I don't see us getting to this this quarter or possibly even next.

**Comment by katrogan** [comment]
My vote would be for having two API calls and avoiding a single frankenstein endpoint since registration isn't really network-constrained.

**Comment by kumare3** [comment]
I think this is better represented and we should instead do the documentation story https://github.com/lyft/flyte/issues/531
