### ISSUE TITLE
[BUG] Node timeout is not being correctly set to default value

### ISSUE THREAD

**Issue by surindersinghp** [lyft/flyte#289]
**Describe the bug**
In wf execution, if node timeout is set to 0, the system bypasses the timeout check instead of using the default value for timeout

**Expected behavior**
Default value was expected to be used, instead timeout check was bypassed.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [x] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
1. Set NodeTimeout to 0.

**Comment by kumare3** [comment]
The issue is resolved and available in 0.3.0
