### ISSUE TITLE
[BUG] FLYTE KUBECTL  cluster unready status ...

### ISSUE THREAD

**Issue by Stallon-niranjan** [lyft/flyte#295]
**Describe the bug**

**Expected behavior**

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [x] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [x] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
1. ...
2. ...

**Screenshots**

**Environment**
**Flyte component**
- [x] Sandbox (local or on one machine)
- [ ] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [x] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**
![Screenshot from 2020-04-24 22-03-46](https://user-images.githubusercontent.com/29067335/80235643-9824cc00-8677-11ea-8aef-500bfcd07f5a.png)

**Comment by Stallon-niranjan** [comment]
flyte workflow are giving error on [3/3] currentAttempt done. Last Error: SYSTEM::containers with unready status: [zs37djubb3-run-edge-detection-3]

mostly... 

do we need any configure changes need for flyte to run locally

**Comment by kumare3** [comment]
@Stallon-niranjan most likely you are unable to pull the cotainer. Can you go to the previous page ("back button") and look for the error message (I know a little weird). That should give you more details about the error.
Another way could be to use
`kubectl get pods -n flytedemo-development`

Please join our slack channel and ping me in the #onboarding I can definitely help

**Comment by kumare3** [comment]
ohh also are you running this on Azure?

**Comment by Stallon-niranjan** [comment]
We are trying to host at Azure, before that we tried to reproduce Flyte Workflows in local..
We need assistance on creating a custom kubectl create -f flyte_generated.yaml . 

Ty In advance @kumare3 

Niranjan

**Comment by Stallon-niranjan** [comment]
as above i tried 
kubectl get pods -n flytedemo-development

I got below details :

(base) niranjan@L-90390725:~/GITHUB/$ kubectl get pods -n flytedemo-development
NAME                              READY   STATUS             RESTARTS   AGE
sgfpo0ou03-return-dataset-0       0/1     ImagePullBackOff   0          42h
sgfpo0ou03-return-dataset-1       0/1     ImagePullBackOff   0          42h
sgfpo0ou03-upper-out-0            0/1     ImagePullBackOff   0          42h
sgfpo0ou03-upper-out-1            0/1     ImagePullBackOff   0          42h
sgfpo0ou03-upper-out-2            0/1     ImagePullBackOff   0          42h
sgfpo0ou03-upper-out-3            0/1     ImagePullBackOff   0          42h
zs37djubb3-run-edge-detection-0   0/1     ImagePullBackOff   0          41h
zs37djubb3-run-edge-detection-1   0/1     ImagePullBackOff   0          41h
zs37djubb3-run-edge-detection-2   0/1     ImagePullBackOff   0          41h
zs37djubb3-run-edge-detection-3   0/1     ImagePullBackOff   0          41h

![Screenshot from 2020-04-26 15-27-56](https://user-images.githubusercontent.com/29067335/80304309-8efc4200-87d2-11ea-9f55-fdb742595c92.png)

**Comment by Stallon-niranjan** [comment]
hi can u send and slack invite  to nirunitk@gmail.com

**Comment by kumare3** [comment]
ohh absolutely. But usually you do not need to send an invite. You directly should get added. Let me send you an invite.

**Comment by kumare3** [comment]
This was because of minikube. When you use minikube, you need to push the image to the docker registry running inside the minikube VM. This is the usual problem with peoples understanding. Sorry for the hole in the docs. We will try to add this to the docs.
