### ISSUE TITLE
Graph Enhancements

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#30]
This is to cover any overflow / nice-to-haves on the graph implementation after the initial usable version. Some ideas:
 * Diving into layers of the graph (i.e. expanding subworkflow nodes inline)
 * Zooming/panning
 * Hover animations, including highlighting data flow in adjacent nodes
 * Animations on nodes in progress
 * Different rendering for nodes which were not executed

**Comment by EngHabu** [comment]
Bug bankruptcy.
