### ISSUE TITLE
[Feature] User vs System errors should be clearly classified and labeled in metrics

### ISSUE THREAD

**Issue by kumare3** [lyft/flyte#300]
**Motivation: Why do you think this is important?**
It is important for the users to know when something failed due to a User error and when something failed due to a System error, without being very low level.

**Goal: What should the final outcome look like, ideally?**
On the UI and in the metrics a user should be able to delineate user and system errors.

**Describe alternatives you've considered**
This needs work in propeller and plugins

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [x] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [x] FlyteAdmin (Control Plane service)
- [x] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
NA

**Additional context**
This will improve visibility greatly

**Is this a blocker for you to adopt Flyte**
NA

**Comment by kumare3** [comment]
A follow up PR is needed to classify dynamic, branch errors too.

**Comment by EngHabu** [comment]
As we discussed offline, to accurately be able to collect this data and build any decisions on it, it's not enough to rely on metrics sampling. We are going to expose the error kind and code as separate columns in Flyte Admin DB in order to be able to build queries/dashboards that are consistent, accurate and reliable.

**Comment by kumare3** [comment]
This is now released and will be available as part of 0.3.0
