### ISSUE TITLE
[BUG] A WF with no nodes is allowed to be registered

### ISSUE THREAD

**Issue by EngHabu** [lyft/flyte#314]
**Describe the bug**
Create a WF with no nodes, register it. Flyte admin will let you register, it'll fail to launch since there are no nodes on the WF. 

**Expected behavior**
It should fail to register.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [X] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [X] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Comment by katrogan** [comment]
@EngHabu mind if I take this one?
