### ISSUE TITLE
[Feature] Execution details UI page should show the top level error message

### ISSUE THREAD

**Issue by kumare3** [lyft/flyte#319]
**Motivation: Why do you think this is important?**
Currently if a workflow fails because of a system error, or during the processing of the workflow itself, the error message is only visible in the List UI for all executions fo the Workflow.

**Goal: What should the final outcome look like, ideally?**
The Details page should show the error message as well, along-with the List UI.

**Describe alternatives you've considered**
NA

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [x] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
NA

**Additional context**
NA

**Is this a blocker for you to adopt Flyte**
NA

**Comment by schottra** [comment]
This is implemented by lyft/flyteconsole#78
