### ISSUE TITLE
[BUG] Multiple input variables are not substituted in the automatic template substitution

### ISSUE THREAD

**Issue by kumare3** [lyft/flyte#320]
**Describe the bug**
When passing variables to command line or passing variables to a Presto query, multiple input variables cannot be substituted. 

Example STatement
```sql   
   SELECT
        COUNT(*) as total_count
    FROM
        hive.events.{{ .Inputs.table }}
    WHERE
        ds = '{{ .Inputs.ds }}' AND hr = {{ .Inputs.hr }}
```

**Expected behavior**
Multiple input variables should be substituted.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [x] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
NA

**Screenshots**
NA

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [ ] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**

**Comment by vlin-lgtm** [comment]
+1, tested this. it works as a charm. thanks!
