### ISSUE TITLE
[Feature] Flytekit-java, add support for S3

### ISSUE THREAD

**Issue by kumare3** [lyft/flyte#332]
**Motivation: Why do you think this is important?**
Lot of users at Lyft would love to adopt 
https://github.com/spotify/flytekit-java, but today flytekit-java is GCP only. We should add support for S3.

**Goal: What should the final outcome look like, ideally?**
Python flytekit would be the only way to use Flyte.

**Describe alternatives you've considered**
NA. Eventually using Flyte-CoPilot would eliminate the need for drivers for each Cloud provider.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [x] Flytekit (SDK) - JAVA
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Additional context**
Java usage is increasing within Lyft. This would help a lot of teams at Lyft

**Is this a blocker for you to adopt Flyte**
NA

**Comment by vlin-lgtm** [comment]
+1.
This will be an important feature (and pre-req) for us to use it at Lyft. A lot of data compute in Lyft's data platform is written in Java and we heavily use AWS.

**Comment by guillaumeguy** [comment]
+1 for prioritization

**Comment by jcarey03** [comment]
+1

**Comment by kumare3** [comment]
I tested this work, the problem is support for TLS today. I guess once we have TLS support we should be able to start using Flytekit-java at lyft

**Comment by kumare3** [comment]
This is working, Closing this out
