### ISSUE TITLE
[Feature] - Reduce Number of Presto Queries in Presto Task

### ISSUE THREAD

**Issue by vlin-lgtm** [lyft/flyte#347]
**Motivation: Why do you think this is important?**
I noticed that when I run a simple presto query, it would become 5 Presto queries behind the scene. It is particularly costly as the backend sends these 5 different queries in 5 separate requests to the Presto server. It is also documented [here](https://lyft.github.io/flyte/user/tasktypes/presto.html). Many of my queries that run in less than 5 seconds in Superset would however run for 3 minutes in a Flyte task. This could be a problem for us as we would like to design a workflow that runs in a fixed schedule and would need to make sure there is no backlog between runs. 

**Goal: What should the final outcome look like, ideally?**
I'd like to see the number of queries reduced as well as the overall response time reduced. 
I'd like to see clearly how much time is spent at each step, for example,
- Flyte making a Presto request, and
- Presto doing computations. 

**Describe alternatives you've considered**
Instead of creating 5 queries, we could reduce it to 2. 
first:
```
CREATE TABLE hive.flyte_temporary_tables."nwdwxc7fjnksj9rtzdvbm894pjlvdgrm_external" (Select * from foo)
WITH (format = 'PARQUET', external_location = 's3://my-s3-bucket/ef/iktp762nhe-p-task-0/')
```
second:
```
DROP TABLE hive.flyte_temporary_tables."nwdwxc7fjnksj9rtzdvbm894pjlvdgrm_external"
```

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [x] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
If you have ideas about the implementation please propose the change. If inline keep it short, if larger then you link to an external document.

**Additional context**

**Is this a blocker for you to adopt Flyte**
Please let us know if this makes it impossible to adopt Flyte

**Comment by wild-endeavor** [comment]
The format should be...
```
CREATE TABLE hive.flyte_temporary_tables."nwdwxc7fjnksj9rtzdvbm894pjlvdgrm_external"
WITH (format = 'PARQUET', external_location = 's3://my-bucket/yt/ongtest1/')
AS (
  SELECT * FROM hive.city.fact_table WHERE ds = '2020-01-06' LIMIT 10
);
```

**Comment by wild-endeavor** [comment]
@vlin-lgtm we're going to release the other change first (the one that makes the username the K8s namespace).  Can you help test that maybe late Tuesday and later?  If that goes well, we'll make this change towards the end of the week.

**Comment by vlin-lgtm** [comment]
Hi @wild-endeavor, thank you for working on this. What other change are you referring to?

**Comment by wild-endeavor** [comment]
Reverting all these... it looks like it doesn't actually work.

**Comment by wild-endeavor** [comment]
Basically we're having quite a bit of difficulty getting the external location to be respected, to the point where maybe it's just not possible with two queries.  The external location is definitely something we need (as different teams might want to write to different places).

Perusing Presto documentation, I get the sense that maybe `create table ... as ...` won't respect the external location flag.  You have to create the table first, and then select into it, for some reason.

Still not entirely sure this is correct, will post more as more information is forthcoming.

**Comment by wild-endeavor** [comment]
Closing this as a Won't Do, we can revisit this in the future if/when Presto supports this pattern.
