### ISSUE TITLE
Sorting/filtering by inputs

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#35]
It's useful to filter executions down by the value of certain inputs. For instance, if a workflow takes a region code as an input and is run frequently with different values for the region code, a user may want to only see executions using one given value of that code ("SEA").

This functionality will require a design spec, since workflows may have many inputs of varying types and indexing across those types and values is non-trivial.

Note: There is an _internal_ design document that could be cleaned up and moved to public in order to provide guidance for this item.

**Comment by EngHabu** [comment]
Bug bankruptcy.
