### ISSUE TITLE
[Feature] Use Redis Sentinel Cluster for cache

### ISSUE THREAD

**Issue by EngHabu** [lyft/flyte#364]
**Motivation: Why do you think this is important?**
As it stands, Flyte Propeller can only connect to a single Redis Instance, if we have a redis cluster or a sentinel cluster, there is no config to enable that.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [X] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Comment by kumare3** [comment]
@EngHabu is this done or still waiting?
