### ISSUE TITLE
[Feature] [UI] Execution Details should show System Metadata, to ease debugging

### ISSUE THREAD

**Issue by kumare3** [lyft/flyte#371]
**Motivation: Why do you think this is important?**
With multi-cluster support, Flyte schedules many workflows across multiple different clusters. When a user has a problem with a workflow (bug, or errors) the first step for the on-call is to find the cluster where the Workflow ended up. This needs access to the database and querying the execution table.
It would be preferable to show the System Execution metadata on the Details page. This is available in the FlyteAdmin API's already https://github.com/lyft/flyteidl/blob/master/protos/flyteidl/admin/execution.proto#L150

**Goal: What should the final outcome look like, ideally?**
The console should show the cluster information (an in the future other system metadata) on the Details page.

**Describe alternatives you've considered**
CLI, but this needs setup and re-write information in the CLI. Users usually share UI links.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [x] FlyteConsole (UI)
- [ ] Other

**Additional context**
NA

**Is this a blocker for you to adopt Flyte**
NA

**Comment by schottra** [comment]
This is implemented by lyft/flyteconsole#78
