### ISSUE TITLE
Basic support for Blob input type in Launch form

### ISSUE THREAD

**Issue by schottra** [lyft/flyte#378]
Related to #22 but being split out as a separate high-impact quick win.

Full support for Blobs will likely involve uploading files to a storage location and receiving back the `uri` where they are stored.

But a very workable basic solution could be achieved by having the user specify a `uri` (string), `format` (string), and selecting one of two values for `dimensionality` (single or multipart). A grouping of 3 simple inputs would allow a user to specify these values when launching.

Validation would only check that the string inputs have values in them. We won't validate the semantics of the values.

**Comment by kumare3** [comment]
This is perfect and IMO fits 90% of the use-cases

**Comment by kumare3** [comment]
@schottra I added it to 0.6.0 :)

**Comment by schottra** [comment]
Implemented by lyft/flyteconsole#86
Available in flyteconsole v0.8.0
