### ISSUE TITLE
[BUG] set_flyte_config_file should fail fast

### ISSUE THREAD

**Issue by katrogan** [lyft/flyte#380]
**Describe the bug**
An invalid filepath passed to [set_flyte_config_file](https://github.com/lyft/flytekit/blob/ea9970ba5e77acd45188d041a03d3dc8db0a71e8/flytekit/configuration/__init__.py#L11) should not be silently swallowed and should error or at least log. 

**Expected behavior**

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [x] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
1. ...
2. ...

**Screenshots**

**Environment**
**Flyte component**
- [x] Sandbox (local or on one machine)
- [x] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**

**Comment by katrogan** [comment]
cc @MarathonDrew @whw

**Comment by whw** [comment]
+1

**Comment by katrogan** [comment]
This is available in flytekit==0.10.4
