### ISSUE TITLE
[Feature]FlyteConsole Launch Form should allow Schema Type

### ISSUE THREAD

**Issue by kumare3** [lyft/flyte#405]
**Motivation: Why do you think this is important?**
Schema Type is a typed variant of MultiPart Blob Type. Thus the console could simply support Schema Type "uri" input as defined [here](https://github.com/lyft/flyteidl/blob/master/protos/flyteidl/core/literals.proto#L51) . The "type" information is already part of the [Variable declaration](https://github.com/lyft/flyteidl/blob/master/protos/flyteidl/core/interface.proto#L13) which is parsed by the UI.

**Goal: What should the final outcome look like, ideally?**
A user should be allowed to enter a simple URI link. The URI should be a prefix (not a file), just like a multi-part blob. No other validation is necessary

**Describe alternatives you've considered**
None

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [x] FlyteConsole (UI)
- [ ] Other

**Additional context**
NA

**Is this a blocker for you to adopt Flyte**
NA

**Comment by kumare3** [comment]
@schottra FYI!

**Comment by schottra** [comment]
This is a subset of lyft/flyte#22. I'll keep this around so it can be closed separately when schema is implemented.

**Comment by schottra** [comment]
Implemented by lyft/flyteconsole#110
Available in flyteconsole v0.16.0
