### ISSUE TITLE
Flytekit Spark entrypoint is broken

### ISSUE THREAD

**Issue by akhurana001** [lyft/flyte#409]
**Describe the bug**
The entrypoint provided via flytekit is broken and leads to failure of spark driver pods.

**Expected behavior**

**Flyte component**
- [ ] Flytekit (Python SDK)

**To Reproduce**
1. ...
2. ...

**Screenshots**

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [ ] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**

**Comment by kumare3** [comment]
this has been merged and documentation now exists in flytesnacks
