### ISSUE TITLE
[Feature] flyte-cli list projects

### ISSUE THREAD

**Issue by wild-endeavor** [lyft/flyte#413]
**Motivation: Why do you think this is important?**
The flyte-cli tool installed by flytekit currently doesn't have a command to list the projects.  We should add this.

**Goal: What should the final outcome look like, ideally?**
`flyte-cli list-projects` should list the current projects.  Admin already has an endpoint that serves this information.  It's just a question of having a command in flyte-cli to hit it.  It's already even in the [Python client](https://github.com/lyft/flytekit/blob/master/flytekit/clients/raw.py#L576).

**Describe alternatives you've considered**
None.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [x] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
NA

**Additional context**
NA

**Is this a blocker for you to adopt Flyte**
NA

**Comment by kumare3** [comment]
This is now part of flytectl
