### ISSUE TITLE
[BUG] flyte-cli and flyteadmin have different representation of certain filters

### ISSUE THREAD

**Issue by kumare3** [lyft/flyte#418]
**Describe the bug**
using flyte-cli to write filters is extremely hard because of no documentation. ALso in the case of "not equals" both expect different syntax - https://github.com/lyft/flyteadmin/blob/45a79dba5a0c64b431263f53d7640af8a8ec8d20/pkg/common/filters.go#L72 (Admin wants ne)
Flytekit wants "neq"

**Expected behavior**
Documentation should have example of each filter.
And filters should be consistent

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [x] Flytekit (Python SDK)
- [x] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Comment by honnix** [comment]
Trying to address this issue in the referencing PR, where I changed `neq` to `ne` in flytekit because I consider it to be never working so it won't break anything, while keeping the API side unchanged for backward compatibility.

**Comment by honnix** [comment]
closed by https://github.com/lyft/flytekit/pull/272
