### ISSUE TITLE
Add Flytesnacks examples for SageMaker

### ISSUE THREAD

**Issue by EngHabu** [lyft/flyte#465]
https://github.com/lyft/flytesnacks/tree/master/plugins/sagemaker/custom

**Comment by bnsblue** [comment]
Ketan wrote up a good flytesnacks example here: https://github.com/lyft/flytesnacks/tree/master/plugins/sagemaker/custom

**Comment by bnsblue** [comment]
This ticket is now complete. Closing. We will create new tickets for flytesnacks when hpo and distributed training for custom training jobs become available.
