### ISSUE TITLE
Add custom labels to projects in Flyte control plane

### ISSUE THREAD

**Issue by kosigz-lyft** [lyft/flyte#474]
**Motivation: Why do you think this is important?**
Providing custom labels to projects will make it easier to attach metadata to Flyte projects in a scalable, general way that would benefit Lyft and other users.

**Goal: What should the final outcome look like, ideally?**
An ideal outcome would involve the Projects data to have a new field that can hold arbitrary K/V pairs for labeling projects, e.g. with contact information, escalation policy, etc.

**Describe alternatives you've considered**
Instead, we can store this metadata outside Flyte.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [x] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**Is this a blocker for you to adopt Flyte**
No; Flyte is currently being used at Lyft.

**Comment by kosigz-lyft** [comment]
https://github.com/lyft/flyteadmin/pull/114

**Comment by kosigz-lyft** [comment]
👀 @EngHabu @kumare3 — updated both of these PR's.

**Comment by kumare3** [comment]
This is part of 0.8.0 release
