### ISSUE TITLE
[BUG] flyteconsole generates wrong link towards stackdriver logs

### ISSUE THREAD

**Issue by honnix** [lyft/flyte#480]
**Describe the bug**
As [this line](https://github.com/lyft/flyteidl/blob/master/clients/go/coreutils/logs/stackdriver.go#L23) says, flyteconsole assumes `logName` to be the pod name, however this has not been the case since certain version (that I'm not sure of, and maybe since deprecating old Stackdriver logging/monitoring) of GKE.

`logName` now simply refers to `projects/<gcp-project>/logs/stderr` or `projects/<gcp-project>/logs/stdout`.

**Expected behavior**
flyteconsole generates the correct link towards Stackdriver logs.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [x] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [x] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
1. Execute a launch plan
2. Pick up any node
3. Click `View Logs`
4. On the sidebar, click `Stackdriver Logs (User)`
5. A new tab/window is opened with no log showing up

**Screenshots**
<img width="672" alt="Screenshot 2020-08-24 at 21 55 24" src="https://user-images.githubusercontent.com/158892/91089910-89b1e580-e654-11ea-9973-4251916fd195.png">

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [x] Cloud hosted
     * [ ] AWS
     * [x] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**
Change the advancedFilter to `resource.labels.pod_name%3D<pod name>` should fix it.

**Comment by honnix** [comment]
Closed by #79

**Comment by honnix** [comment]
@wild-endeavor Sorry for closing this without asking you. Are we supposed to close an issue only after making a new release?

**Comment by wild-endeavor** [comment]
Oh no it's okay.  Thanks!

**Comment by wild-endeavor** [comment]
It's fixed?  Or does issue #79 cover this?

**Comment by honnix** [comment]
Sorry it is a wrong repo. :(
