### ISSUE TITLE
[Feature] Add support for Platform Spark features

### ISSUE THREAD

**Issue by akhurana001** [lyft/flyte#500]
**Motivation: Why do you think this is important?**
This helps platform administrators roll out features where the details should be abstracted out from users like turning on S3Guard support to help solve consistency issues with Spark writing to S3. 

Users would be able to request a number of features to be turned on or off and platform handles the actual spark-config/other details.

**Goal: What should the final outcome look like, ideally?**
Users would be able to request a number of features to be turned on or off and platform handles the actual spark-config/other details.

**Describe alternatives you've considered**

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
If you have ideas about the implementation please propose the change. If inline keep it short, if larger then you link to an external document.

**Additional context**

**Is this a blocker for you to adopt Flyte**
Please let us know if this makes it impossible to adopt Flyte

**Comment by akhurana001** [comment]
This was done.

**Comment by kumare3** [comment]
This is available in v0.8.0
