### ISSUE TITLE
[BUG] Minor UI inconsistency

### ISSUE THREAD

**Issue by katrogan** [lyft/flyte#505]
**Describe the bug**
When the a task fails but the sidebar is open, the node status doesn't update

<img width="1678" alt="Screen Shot 2020-09-09 at 3 29 09 PM" src="https://user-images.githubusercontent.com/953358/92663083-201d1280-f2b5-11ea-8ae8-e77119721ec0.png">

**Expected behavior**

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [x] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
Look at a running task as it transitions to failing

**Screenshots**
See above

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [ ] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**

**Comment by katrogan** [comment]
cc @schottra

**Comment by schottra** [comment]
fixed by lyft/flyteconsole#115
available in flyteconsole v0.17.2
