### ISSUE TITLE
[Backend][Plugin] Create a fail fast plugin

### ISSUE THREAD

**Issue by katrogan** [lyft/flyte#552]
**Why would this plugin be helpful to the Flyte community**
In certain cases it would be useful to leverage [configurable plugins](https://github.com/lyft/flyte/issues/499) as a whitelist mechanism without necessarily having a fallback implementation. In this case a fail-fast plugin implementation would be useful to have as the default plugin implementation for a task type and whitelisted projects/domains could be added for the actual plugin handler.

**Type of Plugin**
- [ ] Web Service (e.g. AWS Sagemaker, GCP DataFlow, Qubole etc...)
- [ ] Kubernetes Operator (e.g. TfOperator, SparkOperator, FlinkK8sOperator, etc...)
- [x] Customized Plugin using native kubernetes constructs
- [ ] Other

**Can you help us with the implementation?**
- [x] Yes
- [ ] No

**Additional context**
...

**Comment by katrogan** [comment]
cc @kumare3 @wild-endeavor

**Comment by kumare3** [comment]
@katrogan can we create this plugin in plugin machinery and instead of no-op its actually a fail fast?

**Comment by katrogan** [comment]
@kumare3 do you mean implement the core pluginmachinery plugin interface https://github.com/lyft/flyteplugins/blob/master/go/tasks/pluginmachinery/core/plugin.go#L36?

**Comment by kumare3** [comment]
@katrogan yes, and keep it as a plugin that is available with pluginmachinery
