### ISSUE TITLE
[BUG] flyteadmin db models seem to have broken gorm indices

### ISSUE THREAD

**Issue by honnix** [lyft/flyte#570]
**Describe the bug**
Not sure I fully understand how gorm works, but according to https://gorm.io/docs/indexes.html, this line doesn't seem to be correct: https://github.com/lyft/flyteadmin/blob/master/pkg/repositories/models/task.go#L8

There are a few places having the same issue.

**Expected behavior**
`index:` is properly prefixed. 

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [x] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
N/A

**Screenshots**
N/A

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [ ] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**
N/A

**Comment by honnix** [comment]
Fixed by https://github.com/lyft/flyteadmin/pull/134

**Comment by katrogan** [comment]
thank you!!
