### ISSUE TITLE
[Feature] Add startup time of a spark job

### ISSUE THREAD

**Issue by catalinii** [lyft/flyte#618]
**Motivation: Why do you think this is important?**
To measure the time spent in kubernetes for a Spark job, we need to identify the time the job was launched by the Spark plugin

**Goal: What should the final outcome look like, ideally?**
Define an environment variable in the spark plugin that indicates the timestamp of the job submission

**Describe alternatives you've considered**
This information does not exist before

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [x ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
Will do the implementation myself

**Additional context**

**Is this a blocker for you to adopt Flyte**
Please let us know if this makes it impossible to adopt Flyte

**Comment by kumare3** [comment]
@catalin23 should we close this issue?

**Comment by catalinii** [comment]
Yes
