### ISSUE TITLE
[Feature] Native map support in flytekit

### ISSUE THREAD

**Issue by honnix** [lyft/flyte#637]
**Motivation: Why do you think this is important?**
Currently a native map type is not supported by flytekit, and a workaround is to use generic as a JSON string. This is not very handy and safe, also it is not compatible with other SDK implementations that support map, such as flytekit-java

**Goal: What should the final outcome look like, ideally?**
Support Python native dict as input and output type, for example:

```
        @inputs(a={Types.String: Types.Integer})
        @outputs(b={Types.String: Types.Integer})
        @python_task
        def square_each(wf_params, a, b):
            b.set(
                {k: v * v for k, v in a.items()}
            )
```

**Describe alternatives you've considered**
Use generic and JSON string.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [x] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
The fix should be straight forward by copying what's being done for list.

**Additional context**
N/A

**Is this a blocker for you to adopt Flyte**
Somewhat, especially when coming to multiple-SDK interoperability.

**Comment by kumare3** [comment]
@honnix can you update the title and maybe add it to the new version of flytekit?

**Comment by honnix** [comment]
I fixed the title. What do you refer to as adding it to the new version?

**Comment by honnix** [comment]
https://github.com/lyft/flyte/projects/7 is this the right one?
