### ISSUE TITLE
Expanded error message collapses when scrolling out of view

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#64]
- Find an execution in the executions table (workflow details page) that has a long error message.
 - Click to expand the error message.
 - Scroll the row out of view
 - Scroll the row back into view

Expected: The error message should still be expanded.

Actual: The error message renders collapsed, but the row is still the size that it would be with the error message expanded. Now the content sits in the middle of a row that is too tall.

**Comment by schottra** [comment]
@kumare3 I don't believe this has been fixed yet. It's a pri3, so it's probably been preempted by more important items.

**Comment by schottra** [comment]
Fixed by lyft/flyteconsole#80, Available in flyteconsole v0.7.3
