### ISSUE TITLE
[BUG] flytekit complains invalid flyte config_file_path specified while the intention is not to have a config file

### ISSUE THREAD

**Issue by honnix** [lyft/flyte#646]
**Describe the bug**
When no `flytekit.config` is packed in an image, flytekit complains about `Invalid flyte config_file_path </path/to/flytekit.config> specified.` upon executing a task.

It could be users intentionally not wanting to use a `flytekit.conf`, so the warning is a bit more scary than it could be.

**Expected behavior**
More mild and less seemingly harmful warning message is logged.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [x] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
1. Create and package a workflow without providing a `flytekit.conf` file
2. Run the workflow and examine the logs

**Screenshots**
N/A

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [ ] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

Any environment

**Additional context**
No.

**Comment by kumare3** [comment]
@honnix thank you for this change. Also, we are trying to get rid of the flytekit.conf at runtime completely

**Comment by honnix** [comment]
Oh I totally forgot about this issue. I think it can be closed. Sorry about that.
