### ISSUE TITLE
Filter/view executions by SHA in Flyte 2.0 UI

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#65]
Already in the cli: 

flyte-cli -h flyte.lyft.net -p flytekit -d development list-executions -f "eq(workflow.version,gitsha)"

 

This is to track potential for this in the UI. 

Customer notes:

 

***NOTE***

The UI can already filter executions by Version, but we don't show versions in the executions table. The work here is mostly for adding that.

Will require a small amount of UX work to determine how to surface versions in the table rows.

**Comment by EngHabu** [comment]
Bug bankruptcy.
