### ISSUE TITLE
[BUG] PR towards flytekit repo triggers two travis-ci builds

### ISSUE THREAD

**Issue by honnix** [lyft/flyte#669]
**Describe the bug**
PR towards flytekit repo triggers two travis-ci builds (see screenshots below).

**Expected behavior**
Note sure this is intended configuration, but if not it should only build on PR branch, not pushed-to branch.

Reference: https://docs.travis-ci.com/user/web-ui/#build-pushed-branches

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [x] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
1. Create a PR branch
2. Push

**Screenshots**
<img width="882" alt="Screenshot 2021-01-14 at 14 54 25" src="https://user-images.githubusercontent.com/158892/104599706-68d84400-5678-11eb-9618-f01cec1e252a.png">

**Environment**
**Flyte component**
- [ ] Sandbox (local or on one machine)
- [ ] Cloud hosted
     * [ ] AWS
     * [ ] GCP
     * [ ] Azure
- [ ] Baremetal
- [ ] Other

**Additional context**
N/A

**Comment by kumare3** [comment]
@honnix Also I think we have to move away from Travis to just use github workflows

**Comment by honnix** [comment]
Oh yeah, they will soon close travis-ci.org.

**Comment by honnix** [comment]
Closed by https://github.com/lyft/flytekit/pull/337
