### ISSUE TITLE
Enable a KickoffTime() like Input that doesn't require a schedule

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#68]
I'd like to be able to have the time a workflow was started as an input to the workflow. I know this works with scheduled workflows, but the use case here is a workflow that isn't scheduled but kicked off ad-hoc. Think of this timestamp as an audit/coordination timestamp.

We attempted to accomplish this using:
 k = Input(Types.Datetime, default=datetime.datetime.now())
 task1(
 t = k
 )
 task2(
 t=k
 ).

Replacing k with datetime.datetime.now() would cause the two tasks to have out of sync times. And leveraging KickoffTime doesn't work. Instead we now have to add a seprate datetime seeing task.

**Comment by EngHabu** [comment]
Bug bankruptcy.
