### ISSUE TITLE
json for launch plans, and workflows

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#72]
The UI should display the spec for launch plans and workflows in addition to tasks.

**Comment by kumare3** [comment]
@schottra whats the status on this? Are we still implementing this?

**Comment by schottra** [comment]
@kumare3 It's low-priority, but also a little vague. I'm not certain what exactly is being asked for here. The issue title says "json for..." but the description references the task spec.
So, I would guess this is asking for workflows to list their inputs/outputs the same way we do for tasks in the list view. And additionally, once we are showing launch plans in the UI again, to do the same for them.

If that's true, this issue should stay open. But it will be a little while before we get to it.

**Comment by EngHabu** [comment]
Bug bankruptcy.
