### ISSUE TITLE
Cant see launch_plan name in Flyte UI for long named workflows

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#85]
when using a workflow with a long name/path, theres no way to see which launch_plan its actually using, since the name is cut off, and also cant select it out of there, or paste a value in there.

![image](https://user-images.githubusercontent.com/1815175/86612821-8ad46980-bf65-11ea-93e4-0557a021b7c8.png)

**Comment by EngHabu** [comment]
Bug bankruptcy.
