### ISSUE TITLE
Add override sha for relaunching workflows via flyte-cli

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#87]
Each month we encounter a set of failed executions (bug in our code, partner changes contract without notice, unexpected scaling limits).  

Flyte-cli has a great interface for getting the list of failures such that they can be piped into the relaunch workflows command, but relaunching doesn't allow us to specify a newer sha where we have fixed the problem causing the failures.  

Our current workaround involves writing a bit of python code, re-familiarizing with the flytekit sdk, etc. which takes us a couple hours every time it happens.

Request is to add a parameter to flyte-cli relaunch for workflow sha to use in lieu of the original one.

**Comment by EngHabu** [comment]
Bug bankruptcy.
