### ISSUE TITLE
Rank Ordering of Inputs in UI Rendering

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#91]
Inputs should be rendered in the order defined in user code for readability. This requires the introduction of a rank field.

**Comment by michaels-lyft** [comment]
+1 Would be awesome if we could do this or be able to have all the required inputs show up before the optional ones.

**Comment by rynld2** [comment]
+1 too. It's fine to me even if we can specify the order in the inputs as another parameter.

**Comment by EngHabu** [comment]
CC @schottra

**Comment by PhoenixLiAtLyft** [comment]
+1 really love to see this feature

**Comment by EngHabu** [comment]
Done

**Comment by michaels-lyft** [comment]
@EngHabu How can we enable this feature?
