### ISSUE TITLE
Plugins should have a standardized interface

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#94]
My recommendation
 - Have a low level plugin interface (Tasks)
 - Have a higher level FlyteK8s interface
 - Have a higher level Services interface

All these interfaces may exist with FlyteIDL or some other place.
The implementation of the machinery that controls them could probably exist with FlytePropeller. The implementations of the plugins could be supplied from various different repositories

**Comment by EngHabu** [comment]
Fixed
