### ISSUE TITLE
Notebook as Flyte Tasks

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#95]

**Comment by EngHabu** [comment]
Are you still planning on finishing [this PR](https://github.com/lyft/flytekit/pull/26), @matthewphsmith?

CC @wild-endeavor @akhurana001 @kumare3 maybe one of you can help push it across the finish line?

**Comment by kumare3** [comment]
I agree we should finish this

**Comment by akhurana001** [comment]
> I agree we should finish this

I can take it up once i get some bandwidth. 
I have good context on the changes to add notebook support as I originally worked on this but not a lot on the overall refactor which touches a bunch of other tasks as well. Will have to take a look and might wanna decouple the two.

**Comment by kumare3** [comment]
@akhurana001 I am going to assign this to you. There is some increase priority for this.
