### ISSUE TITLE
Timedelta Input Type Doesn't Appear to Work in UI

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#97]
Steps:
1. Define a workflow that accepts a Timedelta value as input
2. Launch the workflow using a value that is 999ms or less
3. View the inputs for the resulting execution in the UI

Expected:
Since the launch form documents timedelta as a value in `ms`, all values above `1ms` should render correctly.

Actual:
When the value is below 1 second, it renders as `(unknown)`.

**Comment by schottra** [comment]
This appears to have been fixed by [this commit](https://github.com/lyft/flyteconsole/commit/6d3373c20859fe1767379cf7a3aac8034916548f).

**Comment by schottra** [comment]
Going to reopen. Since the code path in question is used by the inputs/outputs display, it's useful to show the actual millisecond value, instead of just '< 1s'.

**Comment by schottra** [comment]
fixed by lyft/flyteconsole#81
